package com.leibro.Weibo;

import java.sql.*;

public class DB {
	public static Connection getConn() {
		Connection conn = null;
		try {
			Class.forName("com.mysql.jdbc.Driver");
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/weibo","cs4814751","zhulei1993830");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return conn;
	}
	
	public static Statement createStmt(Connection conn) {
		Statement stmt = null;
		try {
			stmt = conn.createStatement();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return stmt;
	}
	
	public static ResultSet executeQuery(Statement stmt,String sql) {
		ResultSet rs = null;
		try {
			rs = stmt.executeQuery(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return rs;
	}
	
	public static ResultSet executeQuery(PreparedStatement pstmt) {
		ResultSet rs = null;
		try {
			rs = pstmt.executeQuery();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return rs;
	}
	
	
	public static void close(Connection conn) {
		try {
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static void close(Statement stmt) {
		try {
			stmt.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static void close(ResultSet rs) {
		try {
			rs.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static void executeUpdate(Statement stmt,String sql) {
		try {
			stmt.executeUpdate(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static void executeUpdate(PreparedStatement pstmt) {
		try {
			pstmt.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public static PreparedStatement preparedStatement(Connection conn,String sql) {
		PreparedStatement pstmt = null;
		try {
			pstmt = conn.prepareStatement(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return pstmt;
	}
	
	public static String getNickName(int userid) {
		Connection conn = DB.getConn();
		Statement stmt = DB.createStmt(conn);
		String nickname = null;
		String sql = "select distinct nickname from user where userid = "+ userid;
		ResultSet rs = DB.executeQuery(stmt, sql);
		try {
			rs.next();
			nickname = rs.getString(1);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		DB.close(rs);
		DB.close(stmt);
		DB.close(conn);
		return nickname;
	}
	
	public static int getPUserid(int pweiboid) {
		int puserid = 0;
		Connection conn = DB.getConn();
		Statement stmt = DB.createStmt(conn);
		String sql = "select userid from mircoblog where id = "+pweiboid;
		ResultSet rs = DB.executeQuery(stmt, sql);
		try {
			rs.next();
			puserid = rs.getInt(1);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return puserid;
	}
	
	public static String getPCont(int pweiboid) {
		String pcont = null;
		Connection conn = DB.getConn();
		Statement stmt = DB.createStmt(conn);
		String sql = "select cont from mircoblog where id = "+pweiboid;
		ResultSet rs = DB.executeQuery(stmt, sql);
		try {
			rs.next();
			pcont = rs.getString(1);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return pcont;
	}
	
	public static PreparedStatement preparedStmtm(Connection conn,String sql,int autoGeneratedKeys) {
		PreparedStatement pstmt = null;
		try {
			pstmt = conn.prepareStatement(sql,autoGeneratedKeys);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return pstmt;
	}
	
	
}
